### ISSUE TITLE
Missing `cate_to_use.txt` File for `3rscan.yaml`

### ISSUE THREAD

**Issue by KuangHaofei** [GradientSpaces/LivingScenes#1]
Dear Author,

Thanks for your great work!

I am currently trying to run the `eval_3rscan.py` script, but I encountered an issue with the 3rscan.yaml configuration file. Specifically, it requires a `category_list` parameter pointing to `/home/liyuanzhu/projects/MA/MORE/data/3RScan/cate_to_use.txt`.

Unfortunately, I was unable to locate this `cate_to_use.txt` file either in the repo provided or within the official 3RScan dataset repo. 
Could you please provide this file?

Thank you very much!

**Comment by Zhu-Liyuan** [comment]
Hi Haofei,

Thank you for your interest and identifying the bug in the code! I have uploaded the cate_to_use.txt file in the recent push.
Should you have any problems, feel free to reach out. I close this issue for now.

Cheers,
Liyuan
