### ISSUE TITLE
 Request for Detailed Steps on Data Processing in 3RScan

### ISSUE THREAD

**Issue by thisparticle** [GradientSpaces/LivingScenes#2]
Hi,

Thank you for your work on this project! I have some questions regarding the data processing workflow in 3RScan, and I would greatly appreciate your guidance:

1. Could you provide detailed steps for processing the 3RScan dataset? For example, after running the 3RScan toolbox, I was able to generate files like `labels.instances.annotated.v2.ply`. What are the subsequent steps to obtain `pointcloud.labels.npz` and `pointcloud.instances.align.ply`?
2. How should I organize or prepare the 3RScan data to directly run your evaluation program? Are there specific emissions or formats required?

I would greatly appreciate any additional resources, instructions, or scripts you could provide to help clarify these steps.

Thank you in advance for your time and assistance!

**Comment by Zhu-Liyuan** [comment]
Hi, 

Thank you for your interest in running our code. Someone asked me similar questions before. I forgot to include the following files in the codebase. You can download them [here](https://drive.google.com/drive/folders/1JWrwBKIBl5QOupl2ex0hV73NpAxjc-Vm?usp=drive_link). They were used to generate the data format you mentioned. 

Best,
Liyuan
